activations:
  - role: user
    activation: readme
    content: |
      # {{ title | raw }}
      
      {{ description | raw }}

  - role: user
    activation: operation
    content: | 
      # {{ operation | raw }}
      
      ----------------------------------------
      | Property        | Value              |
      |-----------------|--------------------|
      | Method          | {{ method | raw }} |
      | Relative Path   | {{ path | raw }}   |
      ----------------------------------------
            
      {{ markdown | raw }}
